#First github actions creation

name: Github_test_workflow

on: 'push'

jobs:

  build:
    
    runs-on: ubuntu-latest
    env:
      MONGO_URL: mongodb://localhost:27017/Drivers
    #Getting an instance of the database working for testing
    services:
      mongodb:
        image: mongo:7.0.3
        ports:
          - 27017:27017
          #db.runCommand checks the database is up and responsive
          #options delays jobs allows for it to wait for database so
          #tests can actually connect to database
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ping : 1});'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v3
        
      - name: using node-version 18.20.8
        uses: actions/setup-node@v3
        
        with:
          node-version: 18.20.8
      
      #install ci for clean package-lock install then test the mocha tests in the repo
      - name: Back End Tests
        working-directory: Application/Front_End/react_front_end
        
        run: npm install && npm ci && npm test -- --watchAll=false
        timeout-minutes: 3


      #Tests for Python Server as awell as install of packages
      - name: python-version '3.14.4'
        uses: actions/setup-python@v4
        with:
          python-version: '3.14.4'

      - name: Server Tests
        working-directory: Application/F1_Server
        run: python3 -m pip install --no-cache-dir -r requirements.txt && pytest test_server.py -v --maxfail=1
        timeout-minutes: 3
       



       
        
